services:

  app:
    ports:
      - "8000:80"

  worker:
    restart: unless-stopped

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: messaging_gateway_redisinsight
    ports:
      - "5540:5540"
    volumes:
      - ${REDISINSIGHT_DATA}:/data
    depends_on:
      - redis

  caddy:
    image: caddy:2.8-alpine
    container_name: caddy
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./compose/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_DATA}:/data
      - ${CADDY_CONFIG}:/config
